version: '3.3'

services:
  app:
    image: ${IMAGE:-app}
    links:
      - mongo
    environment:
      - MONGO_ENABLED=true
      - MONGO_SERVICE_URI=
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - MONGO_SERVICE_DB=app
    ports:
      - "8080:8080"
    command: ${RUN_CMD:-bash -c "dotnet ./bin/Process.dll -c ./config/config.yml"}

  mongo:
    image: mongo:latest
