---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "pip-services-limits-dotnet"
  description: "Limits microservices..."
  
# Console logger
- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

# Performance counters that posts values to log
- descriptor: "pip-services-commons:counters:log:default:1.0"
  level: "trace"

# Prometheus perfomance counters
- descriptor: "pip-services:counters:prometheus:default:1.0"

{{^MONGODB_ENABLED}}{{^FILE_ENABLED}}
# Memory persistence
- descriptor: "pip-services-limits-dotnet:persistence:memory:default:1.0"
{{/FILE_ENABLED}}{{/MONGODB_ENABLED}}

{{#if FILE_ENABLED}}
# File persistence
- descriptor: "pip-services-limits-dotnet:persistence:file:default:1.0"
  path: {{FILE_PATH}}{{^FILE_PATH}}"../Test/Service.Test/Data/limits.test.json"{{/FILE_PATH}}
{{/if}}

{{#if MONGODB_ENABLED}}
# MongoDb persistence
- descriptor: "pip-services-limits-dotnet:persistence:mongodb:default:1.0"
  connection:
    uri: {{MONGODB_SERVICE_URI}}{{^MONGODB_SERVICE_URI}}"mongodb://localhost:27017/test"{{/MONGODB_SERVICE_URI}}
{{/if}}

# Default controller
- descriptor: "pip-services-limits-dotnet:controller:default:default:1.0"

# Shared HTTP Endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: http
    host: 0.0.0.0
    port: {{HTTP_PORT}}{{^HTTP_PORT}}8080{{/HTTP_PORT}}

# HTTP Service V1
- descriptor: "pip-services-limits-dotnet:service:http:default:1.0"

# Hearbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"

# Prometheus metrics service
- descriptor: "pip-services:metrics-service:prometheus:default:1.0"
